# === Etapa 1: Build de la app ===
FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /app

# Copiamos el POM padre
COPY ./pom.xml ./pom.xml /app/

# Copiamos el POM del microservicio
COPY ./hospital-gateway/pom.xml ./hospital-gateway/pom.xml

# Descargamos dependencias
RUN mvn -B dependency:go-offline -f hospital-gateway/pom.xml

# Copiamos el código fuente del microservicio
COPY ./hospital-gateway/src ./hospital-gateway/src

# Compilamos el JAR
RUN mvn clean package -DskipTests -f hospital-gateway/pom.xml

# === Etapa 2: Imagen de ejecución ===
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

# Copiamos el JAR generado de la etapa builder
COPY --from=builder /app/hospital-gateway/target/*.jar hospital-gateway-0.0.1-SNAPSHOT.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","hospital-gateway-0.0.1-SNAPSHOT.jar"]
